### ISSUE TITLE
onConnectionChange callback is called every time activity starts

### ISSUE THREAD

**Issue by ikocijan** [zplesac/android_connectionbuddy#29]
Is there any way to disable this callback being called when activity starts for the first time?

**Comment by zplesac** [comment]
Currently not - it will always fetch the latest network connection state when Activity is created. It's up to you to decide if you want to respond to this information.

I could add a new boolean property to registerForConnectivityEvents() method, so that you can configure whether you want to get notified immediately or only when the network state changes. Would you find this helpful?

**Comment by zplesac** [comment]
Fixed with #30 .
